### ISSUE TITLE
Convert nifti images to minc

### ISSUE THREAD

**Issue by rfcasseb** [SIMEXP/niak#277] opened 2016-12-02 17:53 UTC
Dear experts,

How should I convert nifti images to minc?

I am using ubuntu 14.04.

Thank you!

**Comment by poquirion** [comment] 2016-12-02 20:26
Hello, 
  If you are using the most recent version of NIAK, you can use nifti files and you do not need to convert them.

**Comment by pbellec** [comment] 2016-12-03 15:11
If you would still like to use the minc format, you can use `nii2mnc` on the command line (outside of octave). There is also a tool called `niak_brick_nii2mnc`, it does recursive conversion of an entire directory structure. Anything that is not nifti is copied over, so you have a duplicate of your original dataset, just with mnc files insted of nii ones. FYI there is also a `niak_brick_mnc2nii`.

**Closed by pbellec** 2016-12-03 15:11 UTC
