### ISSUE TITLE
Study effect of ubuntu 16.04 on octave 4.0.0 on the target

### ISSUE THREAD

**Issue by poquirion** [SIMEXP/niak#214] opened 2016-08-03 17:17 UTC
compared to ubuntu 12.04 and octave 3.8.1

**Comment by pbellec** [comment] 2016-08-03 18:01
can you post the location of the test reports?

**Comment by poquirion** [comment] 2016-08-04 18:23
https://simexp.slack.com/archives/docker-niak_psom/p1465834974000014

**Comment by pbellec** [comment] 2016-08-31 14:46
So it looks like we've reached a conclusion on this one. I suggest to leave it open, as we need to nail down compilation flags to ensure better reproducibility. But as we've opted to make the next release with an old version of ubuntu/octave, maybe we should remove this issue from the COG milestone.

**Comment by poquirion** [comment] 2016-08-31 15:17
I have ran test with 12.04 with octave and minc tools 1.9.2 and all is fine. We where not able to accomplish that with ubunu 16.04.

Could the dockerubuntu 16.04 inconsistencies be link to gcc?

Removing this issu from milestone.

**Comment by pbellec** [comment] 2017-05-08 04:17
It is very possible this issue only relates to unstable tests, that I have since fixed. Closing the issue for now.

**Closed by pbellec** 2017-05-08 04:17 UTC
Labels: docker, Release
