### ISSUE TITLE
niak_test_all returns non-zero exit status on successful run

### ISSUE THREAD

**Issue by surchs** [SIMEXP/niak#61] opened 2015-06-19 22:37 UTC
This concerns the current [#43 branch](https://github.com/SIMEXP/niak/tree/iss%2343).

The exit status is ```status = [](0x0)```. This either comes from the pipeline or from within [niak_test_all](https://github.com/SIMEXP/niak/blob/iss%2343/extensions/niak_test/niak_test_all.m#L259-L264). Either way, it makes travis believe the build has failed even though it did not.

**Comment by pbellec** [comment] 2015-06-20 01:54
what version of PSOM are you using? I get the right status locally.

**Comment by surchs** [comment] 2015-06-20 15:27
I'm using the current master branch of psom. Re-ran again with your most recent updates, still get the non-zero status.

**Comment by surchs** [comment] 2015-06-20 17:17
This also seems to be in line with the consistent [failing of the seemingly successful builds](https://travis-ci.org/SIMEXP/niak/builds/67658891) on travis.

**Comment by pbellec** [comment] 2015-06-20 18:25
yep except the build on travis returns 1, while yours returns [], and mine 0. Interesting.

**Comment by surchs** [comment] 2015-06-20 19:13
Ah yes, didn't notice that. Any idea what is going on? There is a status = [] statement in the test_all file, but I doubt that's where this is coming from.

**Comment by pbellec** [comment] 2015-06-20 21:23
Got it. The reason I didn't get the error is that my pipeline manager runs in 'session' mode. There is no way to get a meaningful exit status when the pipeline is running detached from the current session (well, it would actually be feasible, but it's not currently done). I simply changed the travis test file to run the pipeline manager in session mode, I hope this is going to fix the bug. I have no clue why the tests worked before though. Also, I have merged Issue #43 into master already.

**Comment by pbellec** [comment] 2015-06-20 21:48
YAY! build passed.

**Comment by surchs** [comment] 2015-06-20 22:03
That was the issue 43 branch? I only see the master build

**Comment by pbellec** [comment] 2015-06-21 10:25
you would need to merge the changes I made to master into issue #43

**Comment by surchs** [comment] 2015-06-21 14:23
Well I did now but got back to [one of our old problems](https://travis-ci.org/SIMEXP/niak/builds/67730703).

**Comment by pbellec** [comment] 2015-06-21 15:05
Shoot! This error generally happens when there is no space left on the device. I have restarted the build. Let's see what happens.

**Comment by pbellec** [comment] 2015-06-21 15:27
ok the crash seems to be reproducible. Do you have it locally?

**Comment by surchs** [comment] 2015-06-21 15:32
Yes it is - in the docker image. Weird. Maybe the merge reverted something back?

**Comment by pbellec** [comment] 2015-06-21 16:12
OK I also have it locally.

**Comment by pbellec** [comment] 2015-06-21 19:34
I have created an issue in the PSOM repo for this. I also think I have a fix. I am testing it locally now. https://github.com/SIMEXP/psom/issues/22

**Comment by pbellec** [comment] 2015-06-21 20:24
Alright, the build is finally passing. I also replicated it two times locally. I am closing this issue for now.

**Closed by pbellec** 2015-06-21 20:24 UTC
Labels: bug

**Comment by surchs** [comment] 2015-06-21 20:41
Sweet!

**Comment by pbellec** [comment] 2015-06-21 20:55
you may want to merge and delete branch iss#43

**Comment by surchs** [comment] 2015-06-21 20:59
Yeah, I'll do that
